### ISSUE TITLE
Migrate PyPlot code to Plots and recipes

### ISSUE THREAD

**Issue by blegat** [dionysos-dev/Dionysos.jl#121]
- [x] Replace PyPlot with Plots
- [x] Remove Plots as a dependency and use recipes (i.e., rewrite `utils/plotting/plotting.jl`)

**Comment by blegat** [comment]
Might need  to do https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/265

**Comment by adrienbanse** [comment]
No more PyPlot 🎉
