### ISSUE TITLE
Stop hashing the hash

### ISSUE THREAD

**Issue by blegat** [dionysos-dev/Dionysos.jl#18]
The hash of the position is used as a key. Therefore, it is hashed every time it is used which is useless as it already has the properties of a hash. We should define
```julia
struct CellRef
    value::UInt64
end
Base.hash(ref::CellRef) = ref.value
```
and use this as a key in the GridSpace Dict and in the SubSet Set.

**Comment by adrienbanse** [comment]
@blegat Can we close this?

**Comment by blegat** [comment]
Yes :)
