### ISSUE TITLE
Abstraction of input

### ISSUE THREAD

**Issue by blegat** [dionysos-dev/Dionysos.jl#187]
Since we use the input at the center of the cell, using `OUTER` here is wrong:
https://github.com/dionysos-dev/Dionysos.jl/blob/efa0265d1013a13845156e881b954d567e9f2df0/src/problem/optim/abstraction.jl#L42
We should select a cell if the center is in `system.U`, not if it has a nonempty intersection with `system.U`.

**Comment by vdebauche** [comment]
A new incl_mode has been added for the input : we add a cell if the center is in the cell.
