### ISSUE TITLE
Macbook Pro M2 related problems

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#209]
See https://github.com/sisl/CUDD.jl/issues/23. Not possible to precompile Dionysos on a Macbook Pro M2 because of the BDD data structure that uses CUDD.jl.

**Comment by adrienbanse** [comment]
I also get a C error when executing the Gol-Lazar-Belta test `test/examples/test_gol_lazar_belta.jl`. Seems to bug with `optimizer_with_attributes(Dionysos.Problem.BemporadMorari.Optimizer{Float64}, "continuous_solver" => qp_solver, "mixed_integer_solver" => miqp_solver, "indicator" => false, "log_level" => 0)`.

To me also related to the architecture.

[ Info: Solved.
[ Info: Solving... depth: 2
julia(452,0x1dcd09b40) malloc: *** error for object 0xe00000000000000: pointer being freed was not allocated
julia(452,0x1dcd09b40) malloc: *** set a breakpoint in malloc_error_break to debug

signal (6): Abort trap: 6
in expression starting at /Users/adrienbanse/.julia/dev/Dionysos/test/examples/test_gol_lazar_belta.jl:121
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 127035296 (Pool: 126998559; Big: 36737); GC: 47
ERROR: Package Dionysos errored during testing (received signal: 6)

**Comment by blegat** [comment]
About CUDD, we could maybe remove it, we ended up not using BDDs. About BemporadMorary, maybe one of the solver used does not support apple M2, could you check which one it is ? If it is Cbc, we could change it to HiGHS (in any case, we should probably switch from Cbc to HiGHS as HiGHS is better now)
