### ISSUE TITLE
Implement data-driven memory abstractions

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#236]
Implement the two following methods in Dionysos: 
- [ ] Uniform backward-memory DD abstractions (https://arxiv.org/abs/2212.01926)
- [ ] Adaptive forward-memory DD abstractions (https://arxiv.org/abs/2303.17618v2)

**Comment by adrienbanse** [comment]
@blegat It would make sense to contribute to MathematicalSystems.jl to extend to output maps for systems like
x(t+1) = F(x(t))
y(t) = H(x(t)) \in Y, a output set

Would allow to implement for example systems for which a specific partition of the state-space outputs an integer, and another part outputs another (see Figure 4 in https://adrienbanse.github.io/assets/pdf/cdc23_extended.pdf)

**Comment by blegat** [comment]
Not sure what you mean but https://juliareach.github.io/MathematicalSystems.jl/dev/lib/types/#MathematicalSystems.SystemWithOutput allows you to have an output and https://github.com/blegat/HybridSystems.jl allows you to model piecewise state-dependent switching where the sets are from LazySets or Polyhedra for instance

**Comment by adrienbanse** [comment]
> Not sure what you mean but https://juliareach.github.io/MathematicalSystems.jl/dev/lib/types/#MathematicalSystems.SystemWithOutput allows you to have an output and https://github.com/blegat/HybridSystems.jl allows you to model piecewise state-dependent switching where the sets are from LazySets or Polyhedra for instance

`MathematicalSystems.SystemWithOutput` has an attribute `outputmap <: MathematicalSystems.AbstractMap`, but there is no "general structure" that implements `MathematicalSystems.AbstractMap`. 

If one wants to define a system without output that's neither linear nor affine etc., he/she still has the option `MathematicalSystems.BlackBoxDiscreteSystem` for example, which is very general. But there is no such option for systems **with output**. It could be interesting to have such feature in MathematicalSystems.jl.

**Comment by blegat** [comment]
Indeed, it seems to be missing a `MathematicalSystems.BlackBoxMap`, I think it would be a nice addition to MathematicalSystems
