### ISSUE TITLE
Test coverage Hackathon 📈 

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#249]
Let's increase the test coverage for the following

- [x] mapping (@adrienbanse)
- [x] symbolic (@JulienCalbert)
- [x] system (@adrienbanse)
- [x] utils (@vdebauche)
- [x] optim (@JulienCalbert)
- [x] problem (@JulienCalbert)

@vdebauche also for 
- [x] scalar functions
- [x] Lazy set operations

**Comment by vdebauche** [comment]
If it's OK for you, I will try to work on the coverage of 

- [ ] scalar functions 
- [ ] Lazy set operations

**Comment by adrienbanse** [comment]
FYI @JulienCalbert @vdebauche 

From less covered to most covered (in terms of # lines), the remaining parts are 
- utils
- domain
- optim
- symbolic

**Comment by adrienbanse** [comment]
https://github.com/dionysos-dev/Dionysos.jl/pull/297 closes this
