### ISSUE TITLE
Clean controller folder

### ISSUE THREAD

**Issue by JulienCalbert** [dionysos-dev/Dionysos.jl#286]
- Move specific safety and reachability solutions from the controller folder to the SCOTS optimizer folder.
- Standardize the structure of path returned by solvers.

**Comment by JulienCalbert** [comment]
Delete the controller folder. Move the "trajectory" to problem folder.

**Comment by adrienbanse** [comment]
Closed by https://github.com/dionysos-dev/Dionysos.jl/pull/316
