### ISSUE TITLE
Add comments on top of every file in the utils folder

### ISSUE THREAD

**Issue by blegat** [dionysos-dev/Dionysos.jl#288]
https://github.com/dionysos-dev/Dionysos.jl/pull/287 renamed it from `examples` to `utils`

**Comment by adrienbanse** [comment]
@vdebauche 
We weren't talking about the same utils folder during the group meeting
It's in fact the former `examples` folder

**Comment by adrienbanse** [comment]
Closed by https://github.com/dionysos-dev/Dionysos.jl/pull/315
