### ISSUE TITLE
(Re)move BDD dir

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#319]
@blegat @JulienCalbert @egidioln 

What would you think about moving the BDD folder to another directory dionysos-dev/BDDUtils.jl or egidioln/BDDUtils.jl (I believe @egidioln is the author). 

It would be nice to remove once and for all BDDs from Dionysos but it's still interesting code so I feel bad removing it.

**Comment by blegat** [comment]
Yes, we could put everything in a separate repo `dionysos-dev/BDDUtils.jl`

**Comment by egidioln** [comment]
Sorry for the late reply @adrienbanse... I was not the author by the way :P

**Comment by adrienbanse** [comment]
I thought you were! No worries then, everything was moved to https://github.com/dionysos-dev/BDDUtils.jl
