### ISSUE TITLE
SDPA on Julia 1.10

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#331]
See https://github.com/dionysos-dev/Dionysos.jl/pull/329

**Comment by adrienbanse** [comment]
@blegat Any update?

**Comment by blegat** [comment]
The JLL has been updated but there is now a segfault, see the CI results of https://github.com/jump-dev/SDPA.jl/pull/57

**Comment by adrienbanse** [comment]
What about replacing SDPA with another SDP solver for now?

**Comment by blegat** [comment]
Yes, maybe we should try Clarabel
