### ISSUE TITLE
Can we downgrade MeshCat?

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#348]
@blegat @JulienCalbert (idk who worked on this), is there a reason for the compat `MeshCat = "0.15, 0.16"`? I believe it was added by the CompatHelper. 

Our master's student Simon needs to add `ModelingToolkit` in Dionysos and it conflicts with new versions of `MeshCat`

All tests pass with 0.14 version

cc @DeligneS

**Comment by adrienbanse** [comment]
All tests pass with 0.14 version

**Comment by blegat** [comment]
It seems to me that the compat can be removed. It's not used by Dionysos itself but only by one of its examples. Removing it from the `Project.toml` can be a good PR for @DeligneS ;)

**Comment by adrienbanse** [comment]
https://github.com/dionysos-dev/Dionysos.jl/pull/350
