### ISSUE TITLE
Broken doc and CI

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#356]
@blegat @JulienCalbert Any idea why all of a sudden all of our actions are broken?

**Comment by blegat** [comment]
See https://github.com/dionysos-dev/Dionysos.jl/pull/354#issuecomment-2167470544

**Comment by blegat** [comment]
https://github.com/dionysos-dev/Dionysos.jl/pull/359 has fixed the doc build, no idea what happened for the CI build

**Comment by adrienbanse** [comment]
As discussed via e-mails, we drop 1.6 in favor of 1.10 which will solve the CI issue
