### ISSUE TITLE
Abstraction-based Lyapunov function

### ISSUE THREAD

**Issue by blegat** [dionysos-dev/Dionysos.jl#69]
We should build a Lyapunov function from abstractions once https://github.com/dionysos-dev/Dionysos.jl/issues/67 is done using Theorem 8 of https://arxiv.org/abs/2011.11029.
This should allow to use it in the branch and bound thanks to https://github.com/dionysos-dev/Dionysos.jl/issues/68.

In more details, the `Abstraction` submodule of Dionysos generates an abstraction `A` of a system `S`.
The system `S` is an alternating simulation of `A` so by Theorem 8, a Lyapunov function for system `S` can be deduced from an Lyapunov function of `A`. A Lyapunov function for `A` can be computed with a Dijkstra/Bellman-Ford generalization for hyper-graphs similar to what is implemented in https://github.com/dionysos-dev/Dionysos.jl/blob/master/src/Abstraction/controller.jl and https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Bridges/graph.jl

**Comment by JulienCalbert** [comment]
Done in "Alternating simulation on hierarchical abstractions"
