### ISSUE TITLE
Trim and clean the repository?

### ISSUE THREAD

**Issue by guberger** [dionysos-dev/Dionysos.jl#75]
Should we clean a bit the repository, to follow the structure of the workflow diagram? If needed, we can put the files related to SCOTS in a separated repository (in dionysos-dev) until we can insert them in the main code.

**Comment by blegat** [comment]
Yes, I'd like to integrate SCOTS.jl into Dionysos soon so let's try to keep it in.
We could move it to an `Abstraction` subfolder and include it in Dionysos.jl. I think it'd be best to follow the convention that a subfolder corresponds to a submodule.

**Comment by JulienCalbert** [comment]
Done
